### PR TITLE
html5lib -> html

### LINKED ISSUE #21: html5lib package has been renamed to 'html'
At the transition to Angular 4, the bootstrap package ceased to be assembled due to the fact that the html5lib package was changed(https://pub.dartlang.org/packages/html5lib)

### PR DESCRIPTION
**Pull request by jvarness**
Now I could be inherently wrong, but I think this would fix #21

### CODE REVIEW

**Comment by jvarness** [comment]
@richerlariviere any feedback on this?

**Comment by richerlariviere-lightspeed** [comment]
Hey @jvarness thanks for your PR. I'll test this PR this weekend and will probably merge it sunday and update dart package registry.

**Comment by jvarness** [comment]
How do you test a package by the way? With maven I'm used to being able to install a package into my local registry but with pub I have no clue lol

**Comment by richerlariviere-lightspeed** [comment]
To be honest, I always ran the example code and if it worked I merged the PR. There's an interesting page about testing [here](https://www.dartlang.org/guides/testing). We could definitely improve this repo but I need a maintainer. I don't have time to setup a CI integration etc.

**Comment by richerlariviere-lightspeed** [comment]
(I just discovered that I used the wrong Github account lol)

**Comment by jvarness** [comment]
Well I can help setup continuous integration for you if you want some help

**Comment by richerlariviere** [comment]
I added you to the repo collaborators. Have fun :)

**Comment by jvarness** [comment]
Closing because this was fixed with #25

**Pull request closed without merging**
